export const clients = [
  {
    id: 1,
    fullName: {
      first_name: '',
      first_name: 'Adrianne',
      last_name: 'Basso',
    },
    email: 'abasso0@walmart.com',
    gender: 'Genderqueer',
    color: '#86e481',
    shouldColor: false,
    country: 'China',
    avatar: 'https://robohash.org/excepturiearumet.png?size=50x50&set=set1',
  },
  {
    id: 2,
    fullName: {
      first_name: 'Kylila',
      last_name: 'Vakhrushev',
    },
    email: 'kvakhrushev1@businessinsider.com',
    gender: 'Male',
    color: '#33c4e0',
    shouldColor: false,
    country: 'Philippines',
    avatar:
      'https://robohash.org/voluptatesvoluptatumsoluta.png?size=50x50&set=set1',
  },
  {
    id: 3,
    username: 'Basia',
    email: null,
    gender: 'Non-binary',
    color: '#de2c21',
    shouldColor: false,
    country: 'Guatemala',
    avatar: 'https://robohash.org/ducimusipsaid.png?size=50x50&set=set1',
  },
  {
    id: 4,
    fullName: {
      first_name: 'My',
      last_name: 'Pettersen',
    },
    email: 'mpettersen3@merriam-webster.com',
    gender: 'Genderfluid',
    color: '#acb161',
    shouldColor: false,
    country: 'Brazil',
    avatar:
      'https://robohash.org/voluptasrerumdeserunt.png?size=50x50&set=set1',
  },
  {
    id: 5,
    fullName: {
      first_name: 'Sibbie',
      last_name: 'Ballach',
    },
    email: 'sballach4@paypal.com',
    gender: 'Male',
    color: '#a454e2',
    shouldColor: false,
    country: 'France',
    avatar:
      'https://robohash.org/consecteturenimsuscipit.png?size=50x50&set=set1',
  },
  {
    id: 6,
    username: 'Dudley',
    email: 'dleete5@bigcartel.com',
    gender: 'Non-binary',
    color: '#549b53',
    shouldColor: false,
    country: 'Canada',
    avatar: 'https://robohash.org/magnidolorumsint.png?size=50x50&set=set1',
  },
  {
    id: 7,
    fullName: {
      first_name: 'Suzie',
      last_name: 'Tenby',
    },
    email: 'stenby6@google.fr',
    gender: 'Bigender',
    color: '#856b12',
    shouldColor: false,
    country: 'France',
    avatar: 'https://robohash.org/voluptasquicorporis.png?size=50x50&set=set1',
  },
  {
    id: 8,
    fullName: {
      first_name: 'Suzy',
      last_name: 'Apthorpe',
    },
    email: null,
    gender: 'Male',
    color: '#d47837',
    shouldColor: false,
    country: 'Latvia',
    avatar: 'https://robohash.org/quiaabnihil.png?size=50x50&set=set1',
  },
  {
    id: 9,
    fullName: {
      first_name: 'Edwina',
      last_name: 'Rivitt',
    },
    email: 'erivitt8@businessinsider.com',
    gender: 'Genderfluid',
    color: '#8b29cc',
    shouldColor: false,
    country: 'Brazil',
    avatar: 'https://robohash.org/debitistotamenim.png?size=50x50&set=set1',
  },
  {
    id: 10,
    fullName: {
      first_name: 'Niki',
      last_name: 'Mottley',
    },
    email: 'nmottley9@arstechnica.com',
    gender: 'Agender',
    color: '#4e121e',
    shouldColor: false,
    country: 'Ireland',
    avatar: 'https://robohash.org/velitlaborenisi.png?size=50x50&set=set1',
  },
];
